src/OC/PlatformBundle/Entity/Image.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="oc_image")
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

	private $file;

	private $tempFilename;
	
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
	public function getFile() {
		return $this->file;
	}
	public function setFile(UploadedFile $file) {
		$this->file = $file;
		//On vérifie si on avait pas déjà un fichier pour cette entité
        if(null !== $this->url) {
            $this->tempFilename = $this->url;

            $this->url = null;
            $this->alt = null;
        }
	}

	/**
	 * @ORM\PrePersist()
	 * @ORM\PreUpdate()
	 */
	public function preUpload() {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }
    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
	public function upload()
	{
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
	}
    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }
	public function getUploadDir()
	{
		// On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
		return 'uploads/img';
	}
	
	protected function getUploadRootDir()
	{
		// On retourne le chemin relatif vers l'image pour notre code PHP
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}
    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/OC/PlatformBundle/Form/AdvertType.php
<?php

namespace OC\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use OC\PlatformBundle\Repository\CategoryRepository;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    	$pattern = 'D%';
        $builder
        ->add('date', DateTimeType::class)
        ->add('title', TextType::class)
        ->add('author', TextType::class)
        ->add('content', TextareaType::class)
        ->add('image', ImageType::class)
        ->add('categories', EntityType::class, array(
        		'class' => 'OCPlatformBundle:Category',
        		'choice_label' => 'name',
        		'multiple' => true,
        		'query_builder' => function(CategoryRepository $repository) use($pattern){
        			return $repository->getLikeQueryBuilder($pattern);
        		}	
        ))
        ->add('save', SubmitType::class);
        //On récupère notre objet Advert
        $builder->addEventListener(
        		FormEvents::PRE_SET_DATA, //evenement qui nous intéresse
        		function (FormEvent $event) {//fonction a executer
        			//We get the advert objet
        			$advert = $event->getData();
        			
        			if(null === $advert) {
        				return;
        			}
        			//si l'annonce n'est pas publié ou si elle n'a pas d'id (pas en base)
        			if(!$advert->getPublished() || null === $advert->getId()) {
        				//Alors on ajoute le champs published
        				$event->getForm()->add('published', CheckboxType::class, array('required' => false));
        			}
        			else {
        				//sinon, on supprime
        				$event->getForm()->remove('published');
        			}
        			
        });
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OC\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'oc_platformbundle_advert';
    }


}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php

// src/OC/PlateformBundle/Controller/AdvertController.php

namespace OC\PlatformBundle\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Entity\Image;
use OC\PlatformBundle\Entity\Application;
use OC\PlatformBundle\Entity\Skill;
use OC\PlatformBundle\Entity\AdvertSkill;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use OC\PlatformBundle\Form\AdvertType;
use OC\PlatformBundle\Form\AdvertEditType;




class AdvertController extends Controller
{
	public function indexAction($page)
	{
		$nbPerPages = 3;
		//Voir si le nombre de page n'est pas inférieur à 1
		if ($page < 1) {
			//On déclenche une exception NotFoundHttpException
			//La page 404 peut être modifiée
			throw new NotFoundHttpException("Page " . $page . " inexistante");
		}
		//On récupère la liste d'annonce et on l'a passe au template
		// Notre liste d'annonce en dur
		$listAdverts = $this
			->getDoctrine()
			->getManager()
			->getRepository("OCPlatformBundle:Advert")
			->getAdverts($page, $nbPerPages);
		$nbPages = ceil(count($listAdverts)/$nbPerPages);
		if ($page > $nbPages)
		{
			throw new NotFoundHttpException("Page demandé introuvable");
		}
		
		//On en fait que appeller le template
		return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
				'listAdverts' => $listAdverts,
				'nbPages' => $nbPages,
				'page' => $page,
		));
		
	}
	public function viewAction($id)
	{
		$em = $this->getDoctrine()->getManager();
		
		// On récupère l'annonce $id
		$advert = $em
		->getRepository('OCPlatformBundle:Advert')
		->find($id)
		;
		
		if (null === $advert) {
			throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
		}
		
		// On avait déjà récupéré la liste des candidatures
		$listApplications = $em
		->getRepository('OCPlatformBundle:Application')
		->findBy(array('advert' => $advert))
		;
		
		// On récupère maintenant la liste des AdvertSkill
		$listAdvertSkills = $em
		->getRepository('OCPlatformBundle:AdvertSkill')
		->findBy(array('advert' => $advert))
		;
		
		return $this->render('OCPlatformBundle:Advert:view.html.twig', array(
				'advert'           => $advert,
				'listApplications' => $listApplications,
				'listAdvertSkills' => $listAdvertSkills
		));
	}
	
	public function addAction(Request $request) 
	{
		$advert = new Advert();
		
		$form = $this->get('form.factory')->create(AdvertType::class, $advert);
		
		if ($request->isMethod('POST')) {
			$form->handleRequest($request);
			
			//On vérifie la validité du formulaire
			if ($form->isValid()) {
				// Ajoutez cette ligne :
				// c'est elle qui déplace l'image là où on veut les stocker

				//On enregistre l'annonce
				$em = $this->getDoctrine()->getManager();
				$em->persist($advert);
				$em->flush();
				
				$request->getSession()->getFlashBag()->add('notice', 'l\'annonce est bien enregistré');
				
				//On redirige vers la vue
				return $this->redirectToRoute('oc_platform_view', array('id'=>$advert->getId()));
			}
		}
		
		
		//CreateView pour afficher le formulaire tout seul
		return $this->render('OCPlatformBundle:Advert:add.html.twig', array(
			'form' => $form->createView()	
		));
	}
	
	
	
	public function editAction($id, Request $request) 
	{
		$em = $this->getDoctrine()->getManager();
		// Ici, on récupérera l'annonce correspondante à $id
		$advert = $em->getRepository("OCPlatformBundle:Advert")->find($id);

		if (null === $advert)
		{
			throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas !!!!!");
		}
        $form = $this->get('form.factory')->create(AdvertEditType::class, $advert);
		// Même mécanisme que pour l'ajout
		if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em->flush();
			$request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée.');
			
			return $this->redirectToRoute('oc_platform_view', array('id' => $id));
		}
		return $this->render('OCPlatformBundle:Advert:edit.html.twig', array(
				'advert' => $advert,
				'form' => $form->createView()
		));
	}
	
	public function deleteAction(Request $request, $id)
	{
		//On récup l'annonce avec l'id
		$em = $this->getDoctrine()->getManager();
		$advert = $em->getRepository("OCPlatformBundle:Advert")->find($id);
		if (null === $advert)
		{
			throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas !!!!!");
		}
		
		$form = $this->get('form.factory')->create();

		if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()){
		    $em->remove($advert);
		    $em->flush();
		    $request->getSession()->getFlashBag()->add('info', 'Annonce supprimé');
		    return $this->redirectToRoute('oc_platform_home');
        }

		return $this->render('OCPlatformBundle:Advert:delete.html.twig', array(
		    'advert' => $advert,
            'form' => $form->createView()
        ));
	}
	public function viewSlugAction($slug, $year, $_format)
	{
		$content = "On pourrait afficher l'annonce correspondant au
		slug " . $slug . ", créée en " . $year . " et au format " . $_format;
		return new Response($content);
	}
	public function testFindAll()
	{
		$repository = $this->getDoctrine()->getManager()->getRepository("OCPlatformBundle:Advert");
		
		$listAdverts = $repository->myFindAll();
		
		return $listAdverts;
	}
	public function menuAction($limit)
	{
		// On fixe en dur une liste ici, bien entendu par la suite
		// on la récupérera depuis la BDD !
		$listAdverts = $this
			->getDoctrine()
			->getManager()
			->getRepository("OCPlatformBundle:Advert")
			->findBy(
				array(),
				array('date' => 'desc'),
				$limit,
				0
			);
		
		return $this->render('OCPlatformBundle:Advert:menu.html.twig', array(
				// Tout l'intérêt est ici : le contrôleur passe
				// les variables nécessaires au template !
				'listAdverts' => $listAdverts
		));
	}
}

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Ajouter une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Ajouter une annonce</h2>

  {{ include("OCPlatformBundle:Advert:form.html.twig") }}

  <p>
    <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Revenir à la page d'accueil
    </a>
  </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Supprimer une annonce</h2>

    <p>
        Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
    </p>

    {# On met l'id de l'annonce dans la route de l'action du formulaire #}
    <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Modifier une annonce</h2>

  {{ include("OCPlatformBundle:Advert:form.html.twig") }}

  <p>
    Vous éditez une annonce déjà existante, merci de ne pas changer
    l'esprit général de l'annonce déjà publiée.
  </p>

  <p>
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
  </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/form.html.twig #}

<h3>Formulaire d'annonce</h3>

<div class="well">
  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  {# Les erreurs générales du formulaire. #}
  {{ form_errors(form) }}

  {# Génération du label + error + widget pour un champ. #}
  {% if form.date is defined %}
  {{ form_row(form.date) }}
  {% endif %}

  {# Génération manuelle et éclatée : #}
  <div class="form-group">
    {# Génération du label. #}
    {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    {# Affichage des erreurs pour ce champ précis. #}
    {{ form_errors(form.title) }}

    <div class="col-sm-10">
      {# Génération de l'input. #}
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  {# Idem pour un autre champ. #}
  <div class="form-group">
    {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.content) }}
    <div class="col-sm-10">
      {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>
  <div class="form-group">
    {{ form_label(form.image.file, "Fichier", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.image.file) }}
    <div class="col-sm-10">
      {{ form_widget(form.image.file, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>
  

  {{ form_row(form.author) }}
  {{ form_row(form.published) }}
  {{ form_row(form.categories) }}
  <a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>

  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
  {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}

  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
</div>
{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#oc_platformbundle_advert_categories');

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;

    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $('#add_category').click(function(e) {
      addCategory($container);

      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
    if (index == 0) {
      addCategory($container);
    } else {
      // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }

    // La fonction qui ajoute un formulaire CategoryType
    function addCategory($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var template = $container.attr('data-prototype')
        .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
        .replace(/__name__/g,        index)
      ;

      // On crée un objet jquery qui contient ce template
      var $prototype = $(template);

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault(); // évite qu'un # apparaisse dans l'URL
        return false;
      });
    }
  });
</script>

src/OC/PlatformBundle/Resources/views/Advert/index.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/index.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Liste des annonces</h2>

  <ul>
    {% for advert in listAdverts %}
      <li>
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
          {{ advert.title }}
        </a>
        par {{ advert.author }},
        le {{ advert.date|date('d/m/Y') }}
      </li>
    {% else %}
      <li>Pas (encore !) d'annonces</li>
    {% endfor %}
  </ul>
  <ul class="pagination">
  {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
  {% for p in range(1, nbPages) %}
    <li{% if p == page %} class="active"{% endif %}>
      <a href="{{ path('oc_platform_home', {'page': p}) }}">{{ p }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/indexBye.html.twig
<!DOCTYPE html>
<html>
	<head>
		<title>
			Bienvenue sur ma première page avec OpenClassRooms
		</title>
	</head>
	<body>
		<h1>Bye {{ nom }}!</h1>
		<p>
			Allez !! On continue. 
      		Il signifie énormément, car cela veut dire que vous avez
      		réussi à exécuter le programme pour accomplir une tâche simple :
      		afficher ce hello world !
		</p>
	
	</body>


</html>

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig #}

<ul class="nav nav-pills nav-stacked">
  {% for advert in listAdverts %}
    <li>
      <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
        {{ advert.title }}
      </a>
    </li>
  {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

	{# On vérifie que l'image est bien associée à l'annonce #}

  {% if advert.image is not null %}
      <img
              src="{{ asset(advert.image.webPath) }}"
              alt="{{ advert.image.alt }}"
      />
  {% endif %}
  <h2>{{ advert.title }}</h2>
  <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>
  {% if not advert.categories.empty %}
  <p>
  Cette annonce est parue dans les catégories : 
  {% for category in advert.categories %}
  	{{ category.name }} {% if not loop.last %}, {% endif %}
  {% endfor %}
  </p>
  {% endif %}
  <div class="well">
    {{ advert.content }}
  </div>
  <div>
  	{% if listApplications is not null %}
  		{% for application in listApplications %}
  		<div>
  			<p>{{ application.author }} le {{ application.date|date("d/m/Y") }}</p>
  			<p>{{ application.content }}</p>
  		</div>
  		{% endfor %}
  		{% else %}
  		<div><p>Pas de cnadidatures</p></div>
  	{% endif %}
  </div>
  {% if listAdvertSkills|length > 0 %}
  <div>
    Cette annonce requiert les compétences suivantes :
    <ul>
      {% for advertSkill in listAdvertSkills %}
        <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <p>
    <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
    <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-edit"></i>
      Modifier l'annonce
    </a>
    <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
      <i class="glyphicon glyphicon-trash"></i>
      Supprimer l'annonce
    </a>
  </p>

{% endblock %}